import type { Metadata } from "next";
import ReactQueryProvider from "./provider";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cdynnlee",
  description: "Generated by create next app",
  icons: "https://cdynnlee.com/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="h-full min-h-screen bg-custom-100">{children}</div>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
